# serverless.yml
# sls deploy: Deploy python codes to lambda

service: serverless-wcbot

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: server.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
  stage: ${opt:stage, self:provider.stage}
  secrets: ${file(secrets.yml):${self:custom.stage}}

# AWS Lambda with Python 3.6 runtime
provider:
  name: aws
  runtime: python3.6
  stage: dev
  memorySize: 128
  timeout: 30
  versionFunctions: false
  region: us-east-1
  deploymentBucket:
    name: lambda-pycodes-us
  environment:
    FLASK_APP: "${self:custom.secrets.FLASK_APP}"
    FLASK_DEBUG: "${self:custom.secrets.FLASK_DEBUG}"
    DEBUG_MODE: "${self:custom.secrets.DEBUG_MODE}"
    AMZACCESSKEY: "${self:custom.secrets.AWS_ACCESS_KEY_ID}"
    AMZACCESSSECRET: "${self:custom.secrets.AWS_SECRET_ACCESS_KEY}"
    AMZREGION: "${self:custom.secrets.AWS_REGION}"
    AMZBUCKET: "${self:custom.secrets.AWS_BUCKET}"

# Forward all traffic to Flask handle
functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

# Exclude below directories for lamdba deployment
package:
  exclude:
    - secrets.yml
    - shopping-cart/**
    - node_modules/**
    - semantic/**
    - venv/**
